### ISSUE TITLE
Causal Mediation Analysis? 

### ISSUE THREAD

**Issue by XinyueJia** [dscolby/CausalELM.jl#81]
Hi @dscolby, thank you for all the work on this package! I’m using it a lot for causal analysis with immunology data, where it’s common to have multiple mediators. I was wondering if it would be possible to add support for Causal Mediation Analysis in the future, to help capture both direct and indirect effects?

**Comment by dscolby** [comment]
Hi @XinyueJia, Causal Mediation Analysis is useful but I think it would be outside the scope of this package. You might also be interested in Mediation.jl, though.
